use crate::cli::ReportMode;
use hig_core::PackReport;

pub(crate) fn print_report(
    label: &str,
    report: &PackReport,
    mode: ReportMode,
) -> anyhow::Result<()> {
    match mode {
        ReportMode::Short => print_short_report(label, report),
        ReportMode::Verbose => print_verbose_report(label, report),
        ReportMode::Json => print_json_report(label, report),
        ReportMode::Quiet => Ok(()),
    }
}

fn print_short_report(label: &str, report: &PackReport) -> anyhow::Result<()> {
    let seconds = report.duration.as_secs_f64().max(0.000_001);
    let mib = report.input_bytes as f64 / 1024.0 / 1024.0;
    let reduction = if report.input_bytes == 0 {
        0.0
    } else {
        (1.0 - report.archive_bytes as f64 / report.input_bytes as f64) * 100.0
    };
    println!(
        "{label}: files={} input_bytes={} archive_bytes={} reduction={:.2}% duration_ms={:.3} throughput_mib_s={:.2} encryption={:?} speed={:?} cache_hit_rate={:.2}% project_mode_used={} project_generation={}",
        report.input_files,
        report.input_bytes,
        report.archive_bytes,
        reduction,
        report.duration.as_secs_f64() * 1000.0,
        mib / seconds,
        report.encryption_mode,
        report.speed,
        report.cache.hit_rate() * 100.0,
        report.project.project_mode_used,
        report.project.project_generation
    );
    Ok(())
}

fn print_json_report(label: &str, report: &PackReport) -> anyhow::Result<()> {
    let value = serde_json::json!({
        "label": label,
        "report": report,
    });
    println!("{}", serde_json::to_string(&value)?);
    Ok(())
}

fn print_verbose_report(label: &str, report: &PackReport) -> anyhow::Result<()> {
    let seconds = report.duration.as_secs_f64().max(0.000_001);
    let mib = report.input_bytes as f64 / 1024.0 / 1024.0;
    println!(
        "{label}: files={} input_bytes={} archive_bytes={} duration_ms={} throughput_mib_s={:.2} encryption={:?} speed={:?} kdf_profile={:?} session_used={} session_lookup_ms={} session_key_age_secs={} kdf_skipped_by_session={} workers={} writer_strategy={:?} preallocated_bytes={} preallocation_enabled={} cached_payload_opens={} cached_range_opens={} cached_payload_read_bytes={} prefetched_bytes={} direct_writes={} buffered_writes={} peak_pipeline_memory_bytes={} scan_ms={} plan_ms={} kdf_ms={} kdf_overlapped_ms={} read_ms={} compression_ms={} crypto_ms={} pack_blocks_ms={} manifest_ms={} write_ms={} payload_read_ms={} payload_write_ms={} writer_wait_ms={} output_flush_ms={} output_rename_ms={} cache_hits={} cache_misses={} cache_hit_rate={:.2}% hashed_files={} metadata_hash_reuses={} scan_cache_hits={} scan_cache_misses={} scan_cache_hit_rate={:.2}% chunk_metadata_reuses={} chunk_metadata_misses={} trusted_bytes_skipped={} hot_raw_bytes_budget={} hot_raw_bytes={} hot_chunk_raw_bytes={} batch_blocks={} single_blocks={} batched_files={} batch_cache_hits={} batch_cache_misses={} solid_groups={} solid_files={} solid_cache_hits={} solid_cache_misses={} solid_group_bytes={} chunked_files={} chunk_blocks={} chunk_cache_hits={} chunk_cache_misses={} chunk_bytes_reused={} chunk_bytes_compressed={} chunk_plan_cache_hits={} chunk_plan_cache_misses={} sealed_block_hits={} sealed_block_misses={} sealed_bytes_reused={} reencrypted_cache_hits={} payload_source_cache_files={} payload_source_memory_bytes={} payload_source_spool_payloads={} payload_source_spool_bytes={} source_read_bytes={} source_hot_raw_bytes={} payload_memory_mode={:?} payload_memory_budget_bytes={} payload_memory_available_bytes={} cache_pack_hits={} cache_pack_misses={} cache_pack_fallbacks={}",
        report.input_files,
        report.input_bytes,
        report.archive_bytes,
        report.duration.as_millis(),
        mib / seconds,
        report.encryption_mode,
        report.speed,
        report.kdf_profile,
        report.session.session_used,
        report.session.session_lookup_ms,
        report.session.session_key_age_secs,
        report.session.kdf_skipped_by_session,
        report.worker_count,
        report.writer_strategy,
        report.archive_preallocated_bytes,
        report.preallocation_enabled,
        report.cached_payload_open_count,
        report.cached_range_open_count,
        report.cached_payload_read_bytes,
        report.prefetched_bytes,
        report.direct_write_count,
        report.buffered_write_count,
        report.peak_pipeline_memory_bytes,
        report.timings.scan_ms,
        report.timings.plan_ms,
        report.timings.kdf_ms,
        report.timings.kdf_overlapped_ms,
        report.timings.read_ms,
        report.timings.compression_ms,
        report.timings.crypto_ms,
        report.timings.pack_blocks_ms,
        report.timings.manifest_ms,
        report.timings.write_ms,
        report.timings.payload_read_ms,
        report.timings.payload_write_ms,
        report.timings.writer_wait_ms,
        report.timings.output_flush_ms,
        report.timings.output_rename_ms,
        report.cache.hits,
        report.cache.misses,
        report.cache.hit_rate() * 100.0,
        report.scan.hashed_files,
        report.scan.metadata_hash_reuses,
        report.scan.scan_cache_hits,
        report.scan.scan_cache_misses,
        report.scan.scan_cache_hit_rate() * 100.0,
        report.scan.chunk_metadata_reuses,
        report.scan.chunk_metadata_misses,
        report.scan.trusted_bytes_skipped,
        report.scan.hot_raw_bytes_budget,
        report.scan.hot_raw_bytes,
        report.scan.hot_chunk_raw_bytes,
        report.blocks.batch_blocks,
        report.blocks.single_blocks,
        report.blocks.batched_files,
        report.blocks.batch_cache_hits,
        report.blocks.batch_cache_misses,
        report.blocks.solid_groups,
        report.blocks.solid_files,
        report.blocks.solid_cache_hits,
        report.blocks.solid_cache_misses,
        report.blocks.solid_group_bytes,
        report.blocks.chunked_files,
        report.blocks.chunk_blocks,
        report.blocks.chunk_cache_hits,
        report.blocks.chunk_cache_misses,
        report.blocks.chunk_bytes_reused,
        report.blocks.chunk_bytes_compressed,
        report.blocks.chunk_plan_cache_hits,
        report.blocks.chunk_plan_cache_misses,
        report.blocks.sealed_block_hits,
        report.blocks.sealed_block_misses,
        report.blocks.sealed_bytes_reused,
        report.blocks.reencrypted_cache_hits,
        report.blocks.payload_source_cache_files,
        report.blocks.payload_source_memory_bytes,
        report.blocks.payload_source_spool_payloads,
        report.blocks.payload_source_spool_bytes,
        report.blocks.source_read_bytes,
        report.blocks.source_hot_raw_bytes,
        report.blocks.payload_memory_mode,
        report.blocks.payload_memory_budget_bytes,
        report.blocks.payload_memory_available_bytes,
        report.blocks.cache_pack_hits,
        report.blocks.cache_pack_misses,
        report.blocks.cache_pack_fallbacks
    );
    println!(
        "{label}:project mode_used={} generation={} snapshot_valid={} metadata_verified_files={} hash_reuses={} prepared_hits={} prepared_misses={} dirty_files={} dirty_groups={} verify_us={} freeze_us={} retries={}",
        report.project.project_mode_used,
        report.project.project_generation,
        report.project.project_snapshot_valid,
        report.project.project_metadata_verified_files,
        report.project.project_hash_reuses,
        report.project.project_prepared_object_hits,
        report.project.project_prepared_object_misses,
        report.project.project_dirty_files,
        report.project.project_dirty_groups,
        report.project.project_verify_us,
        report.project.project_freeze_us,
        report.project.project_retry_count,
    );
    println!(
        "{label}:us total_us={} daemon_connect_us={} socket_request_us={} socket_connect_us={} socket_pack_roundtrip_us={} daemon_auth_us={} daemon_job_execute_us={} daemon_response_bytes={} client_decode_us={} queue_wait_us={} cache_hot_lookup_us={} walk_us={} metadata_us={} hash_us={} plan_us={} read_us={} compression_us={} crypto_us={} cache_commit_wait_us={} cache_commit_us={} manifest_serialize_us={} manifest_compress_us={} manifest_encrypt_us={} output_create_us={} output_preallocate_us={} output_header_write_us={} output_manifest_write_us={} output_payload_read_us={} output_payload_write_us={} output_write_us={} output_flush_us={} output_fsync_us={} output_rename_us={} response_serialize_us={} unattributed_us={}",
        report.timings_us.total_us,
        report.timings_us.daemon_connect_us,
        report.timings_us.socket_request_us,
        report.timings_us.socket_connect_us,
        report.timings_us.socket_pack_roundtrip_us,
        report.timings_us.daemon_auth_us,
        report.timings_us.daemon_job_execute_us,
        report.timings_us.daemon_response_bytes,
        report.timings_us.client_decode_us,
        report.timings_us.queue_wait_us,
        report.timings_us.cache_hot_lookup_us,
        report.timings_us.walk_us,
        report.timings_us.metadata_us,
        report.timings_us.hash_us,
        report.timings_us.plan_us,
        report.timings_us.read_us,
        report.timings_us.compression_us,
        report.timings_us.crypto_us,
        report.timings_us.cache_commit_wait_us,
        report.timings_us.cache_commit_us,
        report.timings_us.manifest_serialize_us,
        report.timings_us.manifest_compress_us,
        report.timings_us.manifest_encrypt_us,
        report.timings_us.output_create_us,
        report.timings_us.output_preallocate_us,
        report.timings_us.output_header_write_us,
        report.timings_us.output_manifest_write_us,
        report.timings_us.output_payload_read_us,
        report.timings_us.output_payload_write_us,
        report.timings_us.output_write_us,
        report.timings_us.output_flush_us,
        report.timings_us.output_fsync_us,
        report.timings_us.output_rename_us,
        report.timings_us.response_serialize_us,
        report.timings_us.unattributed_us,
    );
    println!(
        "{label}:write_profile temp_create_us={} preallocate_us={} header_write_us={} manifest_write_us={} payload_read_us={} payload_write_us={} payload_memory_write_us={} payload_cached_write_us={} direct_write_us={} buffered_write_us={} writer_wait_us={} flush_us={} fsync_us={} rename_us={} memory_payload_count={} memory_payload_bytes={} cached_file_payload_count={} cached_file_payload_bytes={} cached_range_payload_count={} cached_range_payload_bytes={} direct_writes={} buffered_writes={} coalesced_writes={} coalesced_payloads={} coalesced_bytes={}",
        report.write_profile.temp_create_us,
        report.write_profile.preallocate_us,
        report.write_profile.header_write_us,
        report.write_profile.manifest_write_us,
        report.write_profile.payload_read_us,
        report.write_profile.payload_write_us,
        report.write_profile.payload_memory_write_us,
        report.write_profile.payload_cached_write_us,
        report.write_profile.direct_write_us,
        report.write_profile.buffered_write_us,
        report.write_profile.writer_wait_us,
        report.write_profile.flush_us,
        report.write_profile.fsync_us,
        report.write_profile.rename_us,
        report.write_profile.memory_payload_count,
        report.write_profile.memory_payload_bytes,
        report.write_profile.cached_file_payload_count,
        report.write_profile.cached_file_payload_bytes,
        report.write_profile.cached_range_payload_count,
        report.write_profile.cached_range_payload_bytes,
        report.write_profile.direct_write_count,
        report.write_profile.buffered_write_count,
        report.write_profile.coalesced_write_count,
        report.write_profile.coalesced_payload_count,
        report.write_profile.coalesced_bytes,
    );
    println!(
        "{label}:critical setup_ms={} cache_open_ms={} scan_kdf_wall_ms={} plan_ms={} block_prepare_ms={} cache_commit_ms={} manifest_build_ms={} output_write_ms={} cleanup_ms={} unattributed_ms={} cache_index_format={} cache_index_open_ms={} cache_index_commit_ms={} cache_shards_read={} cache_shards_written={} cache_shard_dirty_count={} cache_commit_mode={} journal_upsert_records={} journal_upsert_paths={} journal_upsert_objects={} journal_upsert_sealed={} l1_index_hits={} l1_metadata_hits={} l1_scratch_reuses={} rayon_pool_reused={} daemon_used={} daemon_lookup_ms={} scheduler_queue_ms={} cpu_worker_wait_ms={} buffer_pool_hits={} buffer_pool_misses={} cache_pack_range_hits={} cache_pack_open_count={} hot_index_reuses={} hot_metadata_reuses={} pipeline_peak_memory_bytes={} header_bytes={} manifest_plain_bytes={} manifest_compressed_bytes={} manifest_protected_bytes={} payload_bytes={} compression_level_counts={:?} legacy_cache_hits={} parameterized_cache_hits={} cache_policy_misses={}",
        report.critical.setup_ms,
        report.critical.cache_open_ms,
        report.critical.scan_kdf_wall_ms,
        report.critical.plan_ms,
        report.critical.block_prepare_ms,
        report.critical.cache_commit_ms,
        report.critical.manifest_build_ms,
        report.critical.output_write_ms,
        report.critical.cleanup_ms,
        report.critical.unattributed_ms,
        report.l2.cache_index_format,
        report.l2.cache_index_open_ms,
        report.l2.cache_index_commit_ms,
        report.l2.cache_shards_read,
        report.l2.cache_shards_written,
        report.l2.cache_shard_dirty_count,
        report.l2.cache_commit_mode,
        report.l2.journal_upsert_records,
        report.l2.journal_upsert_paths,
        report.l2.journal_upsert_objects,
        report.l2.journal_upsert_sealed,
        report.l1.l1_index_hits,
        report.l1.l1_metadata_hits,
        report.l1.l1_scratch_reuses,
        report.l1.rayon_pool_reused,
        report.pipeline.daemon_used,
        report.pipeline.daemon_lookup_ms,
        report.pipeline.scheduler_queue_ms,
        report.pipeline.cpu_worker_wait_ms,
        report.pipeline.buffer_pool_hits,
        report.pipeline.buffer_pool_misses,
        report.pipeline.cache_pack_range_hits,
        report.pipeline.cache_pack_open_count,
        report.pipeline.hot_index_reuses,
        report.pipeline.hot_metadata_reuses,
        report.pipeline.pipeline_peak_memory_bytes,
        report.metadata.header_bytes,
        report.metadata.manifest_plain_bytes,
        report.metadata.manifest_compressed_bytes,
        report.metadata.manifest_protected_bytes,
        report.metadata.payload_bytes,
        report.blocks.compression_level_counts,
        report.blocks.legacy_cache_hits,
        report.blocks.parameterized_cache_hits,
        report.blocks.cache_policy_misses,
    );
    println!(
        "{label}:adaptive_io enabled={} initial_concurrency={} min_concurrency={} max_concurrency={} final_concurrency={} min_observed_concurrency={} max_observed_concurrency={} transitions={} constrained_entries={} recovery_steps={} normal_us={} constrained_us={} total_us={} final_constraint_stage={:?} final_constraint_direction={:?} scan_wall_us={} scan_read_us={} scan_content_hash_us={} stages={} transition_events={}",
        report.adaptive_io.enabled,
        report.adaptive_io.initial_concurrency,
        report.adaptive_io.min_concurrency,
        report.adaptive_io.max_concurrency,
        report.adaptive_io.final_concurrency,
        report.adaptive_io.min_observed_concurrency,
        report.adaptive_io.max_observed_concurrency,
        report.adaptive_io.transitions,
        report.adaptive_io.constrained_entries,
        report.adaptive_io.recovery_steps,
        report.adaptive_io.normal_us,
        report.adaptive_io.constrained_us,
        report.adaptive_io.total_us,
        report.adaptive_io.final_constraint_stage,
        report.adaptive_io.final_constraint_direction,
        report.scan.scan_wall_us,
        report.scan.read_us,
        report.scan.content_hash_us,
        serde_json::to_string(&report.adaptive_io.stages)?,
        serde_json::to_string(&report.adaptive_io.transition_events)?,
    );
    Ok(())
}
